/**
 * Generates and triggers browser download of the text analysis report
 * @param {Object} results Analysis result object
 */
export const exportReport = (results) => {
  if (!results) return;

  const currencySym =
    results.salary_insights?.estimated_salary_range?.currency === "INR"
      ? "₹"
      : "$";

  const reportText = `ProResume AI - Resume Analysis Report
Date: ${new Date().toLocaleDateString()}
Candidate Location: ${results.location || "N/A"}
Experience Level: ${results.experience_level || "N/A"}

==================================================
OVERALL SCORE: ${results.score?.total || 0} / 100
==================================================
Skills: ${results.score?.breakdown?.skills || 0} / 25
Experience: ${results.score?.breakdown?.experience || 0} / 25
Achievements: ${results.score?.breakdown?.achievements || 0} / 20
Format: ${results.score?.breakdown?.format || 0} / 15
Education: ${results.score?.breakdown?.education || 0} / 15

ESTIMATED SALARY RANGE:
${currencySym}${results.salary_insights?.estimated_salary_range?.low?.toLocaleString() || 0} - ${currencySym}${results.salary_insights?.estimated_salary_range?.high?.toLocaleString() || 0} ${results.salary_insights?.estimated_salary_range?.currency || "USD"}

STRONG SKILLS:
${results.skills_analysis?.strong_skills?.join(", ") || "None"}

MISSING SKILLS:
${results.skills_analysis?.missing_skills?.join(", ") || "None"}

IMPROVEMENT TIPS:
${results.detailed_feedback?.improvement_tips?.map((t, i) => `${i + 1}. ${t}`).join("\n") || "None"}

Report generated by ProResume AI - Made by Sanket
`;

  const blob = new Blob([reportText], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `ProResume_AI_Report_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
};
 